version: '3.8'

services:
  # Node A - WireGuard VPN Spoke
  node-a:
    build:
      context: .
      dockerfile: docker/wireguard/Dockerfile
    container_name: wireguard-node-a
    environment:
      - NODE_ID=node-a
      - NODE_IP=10.88.0.11
      - HUB_PUBLIC_IP=${HUB_PUBLIC_IP}
      - HUB_PUBLIC_KEY=${HUB_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY_A}
      - HEALTH_CHECK_PORT=8000
    volumes:
      - ./config/node-a:/etc/wireguard:ro
      - wireguard-logs-a:/var/log/wireguard
    ports:
      - "51820:51820/udp"
      - "8000:8000/tcp"
    networks:
      - wireguard-network
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Node B - WireGuard VPN Spoke
  node-b:
    build:
      context: .
      dockerfile: docker/wireguard/Dockerfile
    container_name: wireguard-node-b
    environment:
      - NODE_ID=node-b
      - NODE_IP=10.88.0.12
      - HUB_PUBLIC_IP=${HUB_PUBLIC_IP}
      - HUB_PUBLIC_KEY=${HUB_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY_B}
      - HEALTH_CHECK_PORT=8000
    volumes:
      - ./config/node-b:/etc/wireguard:ro
      - wireguard-logs-b:/var/log/wireguard
    ports:
      - "51821:51820/udp"
      - "8001:8000/tcp"
    networks:
      - wireguard-network
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Node C - WireGuard VPN Spoke
  node-c:
    build:
      context: .
      dockerfile: docker/wireguard/Dockerfile
    container_name: wireguard-node-c
    environment:
      - NODE_ID=node-c
      - NODE_IP=10.88.0.13
      - HUB_PUBLIC_IP=${HUB_PUBLIC_IP}
      - HUB_PUBLIC_KEY=${HUB_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY_C}
      - HEALTH_CHECK_PORT=8000
    volumes:
      - ./config/node-c:/etc/wireguard:ro
      - wireguard-logs-c:/var/log/wireguard
    ports:
      - "51822:51820/udp"
      - "8002:8000/tcp"
    networks:
      - wireguard-network
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # etcd for Patroni cluster coordination
  etcd:
    build:
      context: ./docker/etcd
      dockerfile: Dockerfile
    container_name: etcd
    environment:
      - ETCD_NAME=etcd-0
      - ETCD_DATA_DIR=/var/lib/etcd
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_PEER_URLS=http://etcd:2380
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_INITIAL_CLUSTER=etcd-0=http://etcd:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_INITIAL_CLUSTER_TOKEN=dstack-cluster
    volumes:
      - etcd-data:/var/lib/etcd
    networks:
      - wireguard-network
    restart: unless-stopped
    ports:
      - "2379:2379"
      - "2380:2380"

  # PostgreSQL Primary with Patroni (Node A)
  postgres-primary:
    build:
      context: ./docker/postgres-patroni
      dockerfile: Dockerfile
    container_name: postgres-primary
    environment:
      - NODE_NAME=postgres-primary
      - NODE_IP=10.88.0.11
      - ETCD_HOST=etcd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=dstack
      - POSTGRES_REPLICATION_PASSWORD=${POSTGRES_REPLICATION_PASSWORD:-replicapass}
    volumes:
      - postgres-data-primary:/var/lib/postgresql/data
      - postgres-backup-primary:/var/lib/pgbackrest
    networks:
      - wireguard-network
    depends_on:
      - node-a
      - etcd
    restart: unless-stopped
    network_mode: "service:node-a"

  # PostgreSQL Replica 1 with Patroni (Node B)
  postgres-replica-1:
    build:
      context: ./docker/postgres-patroni
      dockerfile: Dockerfile
    container_name: postgres-replica-1
    environment:
      - NODE_NAME=postgres-replica-1
      - NODE_IP=10.88.0.12
      - ETCD_HOST=etcd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=dstack
      - POSTGRES_REPLICATION_PASSWORD=${POSTGRES_REPLICATION_PASSWORD:-replicapass}
    volumes:
      - postgres-data-replica-1:/var/lib/postgresql/data
      - postgres-backup-replica-1:/var/lib/pgbackrest
    networks:
      - wireguard-network
    depends_on:
      - node-b
      - etcd
    restart: unless-stopped
    network_mode: "service:node-b"

  # PostgreSQL Replica 2 with Patroni (Node C)
  postgres-replica-2:
    build:
      context: ./docker/postgres-patroni
      dockerfile: Dockerfile
    container_name: postgres-replica-2
    environment:
      - NODE_NAME=postgres-replica-2
      - NODE_IP=10.88.0.13
      - ETCD_HOST=etcd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=dstack
      - POSTGRES_REPLICATION_PASSWORD=${POSTGRES_REPLICATION_PASSWORD:-replicapass}
    volumes:
      - postgres-data-replica-2:/var/lib/postgresql/data
      - postgres-backup-replica-2:/var/lib/pgbackrest
    networks:
      - wireguard-network
    depends_on:
      - node-c
      - etcd
    restart: unless-stopped
    network_mode: "service:node-c"

volumes:
  wireguard-logs-a:
  wireguard-logs-b:
  wireguard-logs-c:
  etcd-data:
  postgres-data-primary:
  postgres-data-replica-1:
  postgres-data-replica-2:
  postgres-backup-primary:
  postgres-backup-replica-1:
  postgres-backup-replica-2:

networks:
  wireguard-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16 