version: '3.8'

services:
  # Node A - WireGuard VPN Spoke
  node-a:
    build:
      context: .
      dockerfile: docker/wireguard/Dockerfile
    container_name: wireguard-node-a
    environment:
      - NODE_ID=node-a
      - NODE_IP=10.88.0.11
      - HUB_PUBLIC_IP=${HUB_PUBLIC_IP}
      - HUB_PUBLIC_KEY=${HUB_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY_A}
      - HEALTH_CHECK_PORT=8000
    volumes:
      - ./config/node-a:/etc/wireguard:ro
      - wireguard-logs-a:/var/log/wireguard
    ports:
      - "51820:51820/udp"
      - "8000:8000/tcp"
    networks:
      - wireguard-network
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Node B - WireGuard VPN Spoke
  node-b:
    build:
      context: .
      dockerfile: docker/wireguard/Dockerfile
    container_name: wireguard-node-b
    environment:
      - NODE_ID=node-b
      - NODE_IP=10.88.0.12
      - HUB_PUBLIC_IP=${HUB_PUBLIC_IP}
      - HUB_PUBLIC_KEY=${HUB_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY_B}
      - HEALTH_CHECK_PORT=8000
    volumes:
      - ./config/node-b:/etc/wireguard:ro
      - wireguard-logs-b:/var/log/wireguard
    ports:
      - "51821:51820/udp"
      - "8001:8000/tcp"
    networks:
      - wireguard-network
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Node C - WireGuard VPN Spoke
  node-c:
    build:
      context: .
      dockerfile: docker/wireguard/Dockerfile
    container_name: wireguard-node-c
    environment:
      - NODE_ID=node-c
      - NODE_IP=10.88.0.13
      - HUB_PUBLIC_IP=${HUB_PUBLIC_IP}
      - HUB_PUBLIC_KEY=${HUB_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY_C}
      - HEALTH_CHECK_PORT=8000
    volumes:
      - ./config/node-c:/etc/wireguard:ro
      - wireguard-logs-c:/var/log/wireguard
    ports:
      - "51822:51820/udp"
      - "8002:8000/tcp"
    networks:
      - wireguard-network
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  wireguard-logs-a:
  wireguard-logs-b:
  wireguard-logs-c:

networks:
  wireguard-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16 